# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(497, 312)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 497, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuDetect = QtWidgets.QMenu(self.menuBar)
        self.menuDetect.setObjectName("menuDetect")
        self.menuPeak = QtWidgets.QMenu(self.menuDetect)
        self.menuPeak.setObjectName("menuPeak")
        self.menuECG = QtWidgets.QMenu(self.menuDetect)
        self.menuECG.setObjectName("menuECG")
        self.menuMeassure = QtWidgets.QMenu(self.menuBar)
        self.menuMeassure.setObjectName("menuMeassure")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/2_openYok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/guardar1Y.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName("actionSave")
        self.actionPeak_2 = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picoP2y.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPeak_2.setIcon(icon2)
        self.actionPeak_2.setObjectName("actionPeak_2")
        self.actionFoot_2 = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pieY.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFoot_2.setIcon(icon3)
        self.actionFoot_2.setObjectName("actionFoot_2")
        self.actionPeak_3 = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ecgY.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPeak_3.setIcon(icon4)
        self.actionPeak_3.setObjectName("actionPeak_3")
        self.actionArrhythmia = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/arritmia2Y.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionArrhythmia.setIcon(icon5)
        self.actionArrhythmia.setObjectName("actionArrhythmia")
        self.actionhhh = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/TipoY.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionhhh.setIcon(icon6)
        self.actionhhh.setObjectName("actionhhh")
        self.actionDichrotic_2 = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/dicrotyellow.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDichrotic_2.setIcon(icon7)
        self.actionDichrotic_2.setObjectName("actionDichrotic_2")
        self.actionDistance = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/med.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDistance.setIcon(icon8)
        self.actionDistance.setObjectName("actionDistance")
        self.actionHeart_rate = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/FC22.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHeart_rate.setIcon(icon9)
        self.actionHeart_rate.setObjectName("actionHeart_rate")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuPeak.addAction(self.actionPeak_2)
        self.menuPeak.addAction(self.actionFoot_2)
        self.menuPeak.addAction(self.actionDichrotic_2)
        self.menuECG.addAction(self.actionPeak_3)
        self.menuDetect.addAction(self.menuECG.menuAction())
        self.menuDetect.addAction(self.menuPeak.menuAction())
        self.menuDetect.addAction(self.actionArrhythmia)
        self.menuMeassure.addAction(self.actionDistance)
        self.menuMeassure.addAction(self.actionHeart_rate)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuDetect.menuAction())
        self.menuBar.addAction(self.menuMeassure.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPeak_3)
        self.toolBar.addAction(self.actionPeak_2)
        self.toolBar.addAction(self.actionFoot_2)
        self.toolBar.addAction(self.actionDichrotic_2)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionArrhythmia)
        self.toolBar.addAction(self.actionhhh)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDistance)
        self.toolBar.addAction(self.actionHeart_rate)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PPG & ECG Annotation Tool"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDetect.setTitle(_translate("MainWindow", "Detect"))
        self.menuPeak.setTitle(_translate("MainWindow", "PPG"))
        self.menuECG.setTitle(_translate("MainWindow", "ECG"))
        self.menuMeassure.setTitle(_translate("MainWindow", "Measure"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionPeak_2.setText(_translate("MainWindow", "Peak"))
        self.actionPeak_2.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionFoot_2.setText(_translate("MainWindow", "Foot"))
        self.actionFoot_2.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionPeak_3.setText(_translate("MainWindow", "Peak R"))
        self.actionPeak_3.setShortcut(_translate("MainWindow", "Alt+E"))
        self.actionArrhythmia.setText(_translate("MainWindow", "Arrhythmia"))
        self.actionArrhythmia.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionhhh.setText(_translate("MainWindow", "type"))
        self.actionhhh.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionDichrotic_2.setText(_translate("MainWindow", "Dichrotic"))
        self.actionDichrotic_2.setShortcut(_translate("MainWindow", "Alt+H"))
        self.actionDistance.setText(_translate("MainWindow", "Distance"))
        self.actionDistance.setIconText(_translate("MainWindow", "Distance"))
        self.actionDistance.setShortcut(_translate("MainWindow", "Alt+D"))
        self.actionHeart_rate.setText(_translate("MainWindow", "Heart rate"))
        self.actionHeart_rate.setIconText(_translate("MainWindow", "Heart rate"))
        self.actionHeart_rate.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

import resources_rc
